# Data {#data}

There is a lack of publicly available, representative datasets for the 
evaluation of data linkage processes[@ferrante2012]. "Gold-standard" linked 
datasets are few and, due to confidentiality laws, sharing seldom possible.

This study used datasets derived from data sampled from Wikimedia's publicly 
available Wikidata database [@wikidata]. A sample of records of Wikidata 
entities classified as human was extracted and processed by the UK Ministry of 
Justice's data linkage team for the purpose of creating one or more linkage 
evaluation dataset(s) [@splink_syn2021]. This processing involved the 
duplication and introduction of typographical and other errors among duplicated 
records, emulating the errors typically found in administrative data sources.

One such linkage evaluation dataset was made available to the author of this 
dissertation by the Ministry of Justice data linkage team. Research ethics 
approval for the use of this data is discussed in Appendix \@ref(ethics).

The supplied linkage evaluation dataset was cleaned of corrupted records 
leaving a study dataset comprised of 113,232 records representing distinct 
individuals (living and dead). The dataset consisted of 8 fields, detailed 
in Table \@ref(tab:fieldlist).

```{r fieldlist}

field_list <- data.frame(`field name` = c("unique entity identifier",
                                          "first name",
                                          "family name",
                                          "date of birth",
                                          "place of birth",
                                          "postcode",
                                          "gender",
                                          "occupation"),
                         `missing values (%)`= c(0,
                                                 0,
                                                 0.7,
                                                 5.3,
                                                 0,
                                                 0,
                                                 1,
                                                 29.6),
                         notes = c("Assigned by Wikidata",
                                   "",
                                   "",
                                   "",
                                   "Randomly assigned if not present in Wikidata source",
                                   "Valid UK postcodes assigned based on, sometimes randomly assigned, place of birth",
                                   "",
                                   ""))

knitr::kable(field_list, 
             align = "lrl",
             col.names = c("field name", 
                           "missing values (%)", 
                           "notes"),
             digits = 1,
             booktabs = TRUE,
             caption = 'List of fields and percentage of missing values in study dataset.') |> 
  kableExtra::kable_styling(latex_options = "striped", bootstrap_options = "striped")

```
