--- 
site: bookdown::bookdown_site
output:
  bookdown::pdf_document2:
    keep_tex: true
    includes:
      before_body: frontpage.tex
      in_header: preamble.tex
documentclass: book
fontsize: 12pt
classoption: twoside
papersize: a4
toc: false
bibliography: [references.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      fig.pos = 'H',
                      fig.align = 'center',
                      out.width = '80%')

```


# Acknowledgements {-}

Many thanks my dissertation supervisor, Dr Jonathan Jordan, for his 
helpful input and guidance at the initiation of this work. Thanks also to the 
numerous colleagues who have shaped my thinking in the course of many 
stimulating conversations on the topic of record linkage.

# Lay Summary of the Dissertation {-}

Target: someone with a good general education, but no university level training in mathematics or statistics.
Summarise: content, method and results (1-2pages in length).

\setcounter{tocdepth}{1}
\tableofcontents

\fancyhead{}
\fancyfoot{}
\pagestyle{fancy}
\fancyhead[RO,LE]{\thepage}
\fancyhead[LO,RE]{\rightmark}

\newcommand{\studentcomment}[1]{\todo[inline, backgroundcolor=blue!30]{\textsc{Student:} #1}}
\newcommand{\DSWcomment}[1]{\todo[inline, backgroundcolor=green!30]{\textsc{DSW:} #1}}
\newcommand{\supcomment}[1]{\todo[inline, backgroundcolor=red!30]{\textsc{Supervisor:} #1}}


\mainmatter
